# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Circadian Light by HomeGlo
version: "6.9.47"
slug: circadian-light
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/rweisbein/circadian-light-by-HomeGlo"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
homeassistant_api: true
map:
  - config:rw
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:lightbulb
panel_title: Circadian Light
panel_admin: false
options:
  manage_integration: true
schema:
  manage_integration: bool
